<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\Container63bdp6l\appProdProjectContainer::class, false)) {
    require __DIR__.'/Container63bdp6l/appProdProjectContainer.php';
}

if (!class_exists(appProdProjectContainer::class, false)) {
    class_alias(\Container63bdp6l\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container63bdp6l\appProdProjectContainer();
