<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerJwbcjix\appProdProjectContainer::class, false)) {
    require __DIR__.'/ContainerJwbcjix/appProdProjectContainer.php';
}

if (!class_exists(appProdProjectContainer::class, false)) {
    class_alias(\ContainerJwbcjix\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJwbcjix\appProdProjectContainer();
